#!/bin/bash
CWD=`dirname "$0"`
. $CWD/env.sh || exit

GIT_BRANCH=origin/main
cd "bikeweek-client" || exit
git reset --hard $GIT_BRANCH
git pull
npm i
npm run build
cd ..

cd "bikeweek-backend" || exit
git reset --hard $GIT_BRANCH
git pull
npm i
cd ..

./stop
./start